# Generated by Django 6.0.2 on 2026-02-25 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PhaseArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('duree_conservation', models.IntegerField(help_text='Durée en années')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='archives.batiment')),
            ],
        ),
        migrations.CreateModel(
            name='ArmoireEtagere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('type_support', models.CharField(choices=[('armoire', 'Armoire'), ('etagere', 'Étagère')], max_length=20)),
                ('capacite', models.IntegerField()),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='archives.salle')),
            ],
        ),
    ]
