# Generated by Django 6.0.2 on 2026-03-02 00:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batiment',
            options={'ordering': ['nom'], 'verbose_name': 'Bâtiment', 'verbose_name_plural': 'Bâtiments'},
        ),
        migrations.AlterModelOptions(
            name='phasearchive',
            options={'ordering': ['ordre', 'nom'], 'verbose_name': "Phase d'archivage", 'verbose_name_plural': "Phases d'archivage"},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['niveau', 'nom'], 'verbose_name': 'Rôle', 'verbose_name_plural': 'Rôles'},
        ),
        migrations.AlterModelOptions(
            name='salle',
            options={'ordering': ['batiment', 'nom'], 'verbose_name': 'Salle', 'verbose_name_plural': 'Salles'},
        ),
        migrations.AddField(
            model_name='batiment',
            name='code',
            field=models.CharField(blank=True, help_text='Code unique du bâtiment (ex: B001)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='batiment',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batiment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='phasearchive',
            name='action_finale',
            field=models.CharField(choices=[('CONSERVER', 'Conservation permanente'), ('ELIMINER', 'Élimination'), ('VERSER', 'Versement aux archives historiques')], default='ELIMINER', max_length=20),
        ),
        migrations.AddField(
            model_name='phasearchive',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='phasearchive',
            name='ordre',
            field=models.IntegerField(default=0, help_text='Ordre dans le cycle de vie'),
        ),
        migrations.AddField(
            model_name='phasearchive',
            name='phase_suivante',
            field=models.ForeignKey(blank=True, help_text='Phase suivante dans le cycle de vie', null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.phasearchive'),
        ),
        migrations.AddField(
            model_name='phasearchive',
            name='type_phase',
            field=models.CharField(choices=[('COURANTE', 'Archive courante'), ('INTERMEDIAIRE', 'Archive intermédiaire'), ('DEFINITIVE', 'Archive définitive'), ('HISTORIQUE', 'Archive historique')], default='COURANTE', max_length=20),
        ),
        migrations.AddField(
            model_name='role',
            name='niveau',
            field=models.IntegerField(default=1, help_text='Niveau hiérarchique (1 = le plus élevé)'),
        ),
        migrations.AddField(
            model_name='salle',
            name='climatisee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salle',
            name='code',
            field=models.CharField(blank=True, help_text='Code unique de la salle (ex: S001)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='salle',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salle',
            name='etage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salle',
            name='superficie',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Superficie en m²', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='salle',
            name='type_salle',
            field=models.CharField(choices=[('ARCHIVE', "Salle d'archive"), ('CONSULTATION', 'Salle de consultation'), ('TRI', 'Salle de tri'), ('NUMERISATION', 'Salle de numérisation')], default='ARCHIVE', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='salle',
            unique_together={('batiment', 'nom')},
        ),
        migrations.CreateModel(
            name='Armoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Code unique de l'armoire (ex: ARM-001)", max_length=50, unique=True)),
                ('type_armoire', models.CharField(choices=[('METAL', 'Métallique'), ('BOIS', 'Bois'), ('COMPACT', 'Compact à rayonnages mobiles'), ('MURAL', 'Mural')], default='METAL', max_length=20)),
                ('hauteur', models.DecimalField(blank=True, decimal_places=2, help_text='Hauteur en cm', max_digits=6, null=True)),
                ('largeur', models.DecimalField(blank=True, decimal_places=2, help_text='Largeur en cm', max_digits=6, null=True)),
                ('profondeur', models.DecimalField(blank=True, decimal_places=2, help_text='Profondeur en cm', max_digits=6, null=True)),
                ('code_barres', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('qr_code', models.TextField(blank=True, help_text='QR code en format texte ou URL')),
                ('description', models.TextField(blank=True)),
                ('date_installation', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armoires', to='archives.salle')),
            ],
            options={
                'verbose_name': 'Armoire',
                'verbose_name_plural': 'Armoires',
                'ordering': ['salle', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Etagere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text="Numéro de l'étagère dans l'armoire")),
                ('code_barres', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('capacite_max_boites', models.IntegerField(default=10, help_text='Nombre maximum de boîtes')),
                ('occupation_actuelle', models.IntegerField(default=0, help_text='Nombre de boîtes actuellement')),
                ('hauteur_sol', models.DecimalField(blank=True, decimal_places=2, help_text='Hauteur par rapport au sol en cm', max_digits=6, null=True)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('armoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etageres', to='archives.armoire')),
            ],
            options={
                'verbose_name': 'Étagère',
                'verbose_name_plural': 'Étagères',
                'ordering': ['armoire', 'numero'],
                'unique_together': {('armoire', 'numero')},
            },
        ),
        migrations.DeleteModel(
            name='ArmoireEtagere',
        ),
    ]
