# Generated by Django 6.0.2 on 2026-03-03 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_alter_batiment_options_alter_phasearchive_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['nom'], 'verbose_name': 'Rôle', 'verbose_name_plural': 'Rôles'},
        ),
        migrations.RemoveField(
            model_name='armoire',
            name='hauteur',
        ),
        migrations.RemoveField(
            model_name='armoire',
            name='largeur',
        ),
        migrations.RemoveField(
            model_name='armoire',
            name='profondeur',
        ),
        migrations.RemoveField(
            model_name='armoire',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='etagere',
            name='hauteur_sol',
        ),
        migrations.RemoveField(
            model_name='role',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='climatisee',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='superficie',
        ),
        migrations.AlterField(
            model_name='phasearchive',
            name='action_finale',
            field=models.CharField(choices=[('CONSERVER', 'Archiver définitivement'), ('ELIMINER', 'Élimination')], default='ELIMINER', max_length=20),
        ),
        migrations.AlterField(
            model_name='phasearchive',
            name='type_phase',
            field=models.CharField(choices=[('COURANTE', 'Archive courante'), ('INTERMEDIAIRE', 'Archive intermédiaire'), ('DEFINITIVE', 'Archive définitive')], default='COURANTE', max_length=20),
        ),
        migrations.CreateModel(
            name='Boitier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idboit', models.CharField(help_text='Identifiant unique du boîtier (ex: BOX-2024-001)', max_length=50, unique=True, verbose_name='ID Boîtier')),
                ('code_barre', models.CharField(help_text='Code-barres unique pour scan', max_length=100, unique=True, verbose_name='Code-barres')),
                ('titre', models.CharField(help_text='Titre descriptif du boîtier', max_length=200, verbose_name='Titre')),
                ('capacite', models.IntegerField(help_text='Nombre maximum de dossiers que peut contenir le boîtier', verbose_name='Capacité')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('PLEIN', 'Plein'), ('ARCHIVE', 'Archivé'), ('EN_TRANSFERT', 'En transfert'), ('EN_PREPARATION', 'En préparation')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('armoire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boitiers', to='archives.armoire', verbose_name='Armoire')),
                ('etagere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boitiers', to='archives.etagere', verbose_name='Étagère')),
            ],
            options={
                'verbose_name': 'Boîtier',
                'verbose_name_plural': 'Boîtiers',
                'ordering': ['idboit'],
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDossier', models.CharField(help_text='Identifiant unique du dossier (ex: DOS-2024-001)', max_length=50, unique=True, verbose_name='ID Dossier')),
                ('reference', models.CharField(help_text='Référence administrative du dossier', max_length=100, unique=True, verbose_name='Référence')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateField(help_text='Date de création du dossier', verbose_name='Date de création')),
                ('date_cloture', models.DateField(blank=True, null=True, verbose_name='Date de clôture')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('CLOS', 'Clos'), ('TRANSFERE', 'Transféré'), ('DETRUIT', 'Détruit')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('niveau_confidentialite', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNE', 'Interne'), ('CONFIDENTIEL', 'Confidentiel'), ('SECRET', 'Secret')], default='INTERNE', max_length=20, verbose_name='Niveau de confidentialité')),
                ('boitier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='archives.boitier', verbose_name='Boîtier')),
                ('phase_archive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='archives.phasearchive', verbose_name="Phase d'archive")),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['reference'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDoc', models.CharField(help_text='Identifiant unique du document', max_length=50, unique=True, verbose_name='ID Document')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('titre', models.CharField(max_length=500, verbose_name='Titre')),
                ('date_creation', models.DateField(verbose_name='Date de création')),
                ('niv_confidentialite', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNE', 'Interne'), ('CONFIDENTIEL', 'Confidentiel'), ('SECRET', 'Secret')], default='INTERNE', max_length=20, verbose_name='Niveau de confidentialité')),
                ('version', models.IntegerField(default=1, help_text='Numéro de version du document', verbose_name='Version')),
                ('type_document', models.CharField(choices=[('CONTRAT', 'Contrat'), ('FACTURE', 'Facture'), ('RAPPORT', 'Rapport'), ('COURRIER', 'Courrier'), ('FORMULAIRE', 'Formulaire'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('auteur', models.CharField(blank=True, max_length=200, verbose_name='Auteur')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/', verbose_name='Fichier')),
                ('taille_fichier', models.BigIntegerField(blank=True, null=True, verbose_name='Taille (octets)')),
                ('hash_fichier', models.CharField(blank=True, max_length=64, verbose_name='Hash SHA-256')),
                ('date_entree', models.DateTimeField(auto_now_add=True, verbose_name="Date d'entrée")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('historique_versions', models.JSONField(blank=True, default=list, verbose_name='Historique des versions')),
                ('historique_consultations', models.JSONField(blank=True, default=list, verbose_name='Historique des consultations')),
                ('phase_archive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='archives.phasearchive', verbose_name="Phase d'archive")),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='archives.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date_creation', 'reference'],
            },
        ),
        migrations.AddIndex(
            model_name='boitier',
            index=models.Index(fields=['idboit'], name='archives_bo_idboit_7169a7_idx'),
        ),
        migrations.AddIndex(
            model_name='boitier',
            index=models.Index(fields=['code_barre'], name='archives_bo_code_ba_90e3e4_idx'),
        ),
        migrations.AddIndex(
            model_name='boitier',
            index=models.Index(fields=['statut'], name='archives_bo_statut_cc25a6_idx'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['idDossier'], name='archives_do_idDossi_3c3078_idx'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['reference'], name='archives_do_referen_e9cb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['statut'], name='archives_do_statut_700756_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['idDoc'], name='archives_do_idDoc_06fa28_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['reference'], name='archives_do_referen_d9d0d0_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['phase_archive'], name='archives_do_phase_a_5257db_idx'),
        ),
    ]
